
Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/Debugger:
  DebuggerMethods:
    Pry: ~
